fix: Add support for conditional per_folder_admins and all_folder_adm…
terraform-google-modules/terraform-google-folders pull request #88
Opened 2024-09-26 17:17 UTC by MohdUmar20

Issue reported by other user as well earlier : https://github.com/terraform-google-modules/terraform-google-folders/issues/69

### Overview:
This PR introduces a modification to the existing IAM bindings for Google Folders. It enables the ability to conditionally apply `per_folder_admins` and `all_folder_admins` roles based on user input.

### Changes:
1. **Logic:**
   - If `per_folder_admins` is provided, it applies to specific folders.
   - If `per_folder_admins` is not provided, it will be skipped.
   - `all_folder_admins` is applied to all folders if provided.
   - If `all_folder_admins` is not provided, it is skipped.

2. **Logic for Roles:**
   - If roles are not provided in `per_folder_admins`, it defaults to the `folder_admin_roles` list.
   
   #### Example:

```hcl
module "folders" {
  source  = "terraform-google-modules/folders/google"
  version = "~> 5.0"

  parent              = "organizations/${var.org_id}"
  names               = ["Core", "Prod"]
  deletion_protection = false
  set_roles           = true

  folder_admin_roles = [
    "roles/owner",
    "roles/resourcemanager.projectCreator",
  ]

  per_folder_admins = {
    Core = {
      members = ["group:admin-core@example.com"]
    }
  }

  all_folder_admins = ["group:admin-all@example.com"]
}

2024-09-26 17:27 UTC, MohdUmar20 commented
CLA is signed by me now.
![image](https://github.com/user-attachments/assets/9df7fd28-d4fc-4d8d-965b-0972ec37b8e1)

2024-09-26 17:34 UTC, MohdUmar20 commented
@g-awmalik @apeabody : Please review and let me know if there is anything else i need to add as its my first contribution to GCP Project.

2024-09-26 17:56 UTC, apeabody requested changes
Thanks for the contribution @MohdUmar20!

From the lint test:
```
Working in . using /root/tflint/.tflint.module.hcl...
1 issue(s) found:

Warning: [Fixable] Interpolation-only expressions are deprecated in Terraform v0.12.14 (terraform_deprecated_interpolation)

  on main.tf line 63:
  63:   for_each = var.set_roles && length(local.folder_admin_roles_combined) > 0 ? zipmap([for i, v in local.folder_admin_roles_combined : "${i}"], local.folder_admin_roles_combined) : {}

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.9.1/docs/rules/terraform_deprecated_interpolation.md

tflint failed . 
```

2024-09-26 18:06 UTC, MohdUmar20 commented
@apeabody  : thanks for quick response, updated to fix the interpolation syntax typo.

2024-09-26 18:29 UTC, apeabody commented
/gcbrun

2024-09-26 18:39 UTC, apeabody commented
From the tests:

```
$$$$$$ Verifying the 'simple_example local' system...
Skipping profile: 'inspec-gcp' on unsupported platform: 'alpine/3.20.3'.

Profile:   simple_example
Version:   (not specified)
Target:    local://
Target ID: 23ac897d9c2718bb0133acafeb16a671dd1fd41c16b467a66f278f2f46d4f2be

  ×  gcloud: gcloud (1 failed)
     ✔  Command: `gcloud resource-manager folders list --folder=665285504639` exit_status is expected to eq 0
     ✔  Command: `gcloud resource-manager folders list --folder=665285504639` stderr is expected to eq ""
     ✔  Command: `gcloud resource-manager folders list --folder=665285504639` stdout is expected to include "dev"
     ✔  Command: `gcloud resource-manager folders list --folder=665285504639` stdout is expected to include "production"
     ✔  Command: `gcloud resource-manager folders list --folder=665285504639` stdout is expected to include "staging"
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/621801115109` exit_status is expected to eq 0
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/621801115109` stderr is expected to eq ""
     ×  Command: `gcloud alpha resource-manager folders get-iam-policy folders/621801115109` stdout is expected to include "group:test-gcp-developers@test.blueprints.joonix.net"
     expected "bindings:\n- members:\n  - group:test-gcp-org-admins@test.blueprints.joonix.net\n  role: roles/compu...ueprints.joonix.net\n  role: roles/resourcemanager.projectCreator\netag: BwYjCgLMaw0=\nversion: 1\n" to include "group:test-gcp-developers@test.blueprints.joonix.net"
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/599548574228` exit_status is expected to eq 0
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/599548574228` stderr is expected to eq ""
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/599548574228` stdout is expected to include "group:test-gcp-qa@test.blueprints.joonix.net"
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/34097128227` exit_status is expected to eq 0
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/34097128227` stderr is expected to eq ""
     ✔  Command: `gcloud alpha resource-manager folders get-iam-policy folders/34097128227` stdout is expected to include "group:test-gcp-ops@test.blueprints.joonix.net"


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 13 successful, 1 failure, 0 skipped
>>>>>> Verifying the 'simple_example local' system failed:
```

2024-09-27 10:05 UTC, MohdUmar20 commented
@apeabody  : Can you check now please.

Added more robust error handling so that in case there is duplicate members, it will identify and only try to add once.
tested all scenario for all_folder_admins and per_folder_admins variables- 

1) If both variables provided.
2) if only all_folder_admins provided.
3)  if only per_folder_admins provided.
4) if both variables not provided.

2024-09-27 16:05 UTC, apeabody commented on main.tf
> +    if length(var.all_folder_admins) > 0 && !contains(keys(var.per_folder_admins), folder)
You might also consider running `distinct()` on the final list as a simpler solution to eliminating duplicates.

2024-09-27 16:07 UTC, apeabody commented
/gcbrun

2024-09-27 16:12 UTC, apeabody commented
Hi @MohdUmar20 

Minor lint note:

```
Running terraform fmt
main.tf
--- old/main.tf
+++ new/main.tf
@@ -61,7 +61,7 @@
 # https://cloud.google.com/resource-manager/docs/access-control-folders#granting_folder-specific_roles_to_enable_project_creation
 
 locals {
-  folder_iam_bindings = var.set_roles && length(local.folder_admin_roles_combined) > 0 ? { for i, role in local.folder_admin_roles_combined : "${role.name}-${role.role}" => role }: {}
+  folder_iam_bindings = var.set_roles && length(local.folder_admin_roles_combined) > 0 ? { for i, role in local.folder_admin_roles_combined : "${role.name}-${role.role}" => role } : {}
 }
 
 resource "google_folder_iam_binding" "owners_combined" {
Error: terraform fmt failed with exit code 3
```

2024-09-27 16:49 UTC, apeabody commented
/gcbrun

2024-09-27 20:08 UTC, MohdUmar20 commented
@apeabody : Thanks for all support. Now all checks seems to be passed. Do you have any other comment over the PR or we are good ?

2024-09-30 15:47 UTC, MohdUmar20 commented
@apeabody  Thanks for all support. Now all checks seems to be passed. Do you have any other comment over the PR or we are good for the merge?

2024-10-01 15:40 UTC, MohdUmar20 commented
@apeabody  : Hello, Did you managed to check ?

2024-10-01 18:34 UTC, apeabody approved these changes
Thanks for the contribution @MohdUmar20!

2024-10-01 18:34 UTC, merged